services:
  clean_analysis:
    image: hannnnnnk/bee_population_analysis:latest
    volumes:
      - ./:/home/jovyan
    stdin_open: true
    tty: true
    depends_on:
      - init_db
    command: make clean

  run_analysis:
    image: hannnnnnk/bee_population_analysis:latest
    volumes:
      - ./:/home/jovyan
    stdin_open: true
    tty: true
    depends_on:
      - init_db
    command: make all
    
  init_db:
    image: mysql:latest
    volumes:
      - ./:/home/jovyan
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bee_population_analysis_db
      MYSQL_USER: system
      MYSQL_PASSWORD: 123456


    

