SET FOREIGN_KEY_CHECKS=0; 
DROP TABLE IF EXISTS Detect; 
DROP TABLE IF EXISTS MonitorStation; 
DROP TABLE IF EXISTS Bee; 
DROP TABLE IF EXISTS GasConditions; 
DROP TABLE IF EXISTS Influence; 
DROP TABLE IF EXISTS Monitor; 
DROP TABLE IF EXISTS Kills; 
DROP TABLE IF EXISTS RiskFactors; 
DROP TABLE IF EXISTS Parasite; 
DROP TABLE IF EXISTS Pesticide; 
SET FOREIGN_KEY_CHECKS=1; 
CREATE TABLE MonitorStation (CentroidLongitude DECIMAL, CentroidLatitude DECIMAL, Year INTEGER, AverageTemperature DECIMAL, PRIMARY KEY (CentroidLongitude, CentroidLatitude, Year));
CREATE TABLE Bee (State VARCHAR(255), Year INTEGER, Colony INTEGER, MaxColony INTEGER, LostColony INTEGER, PercentLost DECIMAL, AddColony INTEGER, PercentRenovated DECIMAL, PercentLostByDisease DECIMAL, PRIMARY KEY (State, Year));
CREATE TABLE Detect (CentroidLongitude DECIMAL, CentroidLatitude DECIMAL, StationYear INTEGER, BeeState VARCHAR(255), BeeYear INTEGER, PRIMARY KEY (CentroidLongitude, CentroidLatitude, StationYear, BeeState, BeeYear), FOREIGN KEY (BeeState, BeeYear) REFERENCES Bee(State, Year), FOREIGN KEY (CentroidLongitude, CentroidLatitude, StationYear) REFERENCES MonitorStation(CentroidLongitude, CentroidLatitude, Year));
CREATE TABLE GasConditions (Name VARCHAR(255), State VARCHAR(255), Year INTEGER, MeanValue DECIMAL, AverageAQI DECIMAL, PRIMARY KEY (Name, State, Year));
CREATE TABLE Influence (GasPollutantsYearAffected INTEGER, GasPollutantsStateAffected VARCHAR(255), BeeState VARCHAR(255), BeeYear INTEGER, GasPollutantsName VARCHAR(255), PRIMARY KEY (GasPollutantsYearAffected, GasPollutantsStateAffected, BeeState, BeeYear, GasPollutantsName), FOREIGN KEY (BeeState, BeeYear) REFERENCES Bee(State, Year), FOREIGN KEY (GasPollutantsName, GasPollutantsStateAffected, GasPollutantsYearAffected) REFERENCES GasConditions(Name, State, Year));
CREATE TABLE RiskFactors (State VARCHAR(255), Year INTEGER, Name VARCHAR(255), PRIMARY KEY (State, Year)); 
CREATE TABLE Monitor (CentroidLongitude DECIMAL, CentroidLatitude DECIMAL, StationYear INTEGER, RiskFactorsReportedYear INTEGER, RiskFactorsReportedState VARCHAR(255),  PRIMARY KEY (CentroidLongitude, CentroidLatitude, StationYear, RiskFactorsReportedYear, RiskFactorsReportedState), FOREIGN KEY (RiskFactorsReportedState, RiskFactorsReportedYear) REFERENCES RiskFactors(State, Year), FOREIGN KEY (CentroidLongitude, CentroidLatitude, StationYear) REFERENCES MonitorStation(CentroidLongitude, CentroidLatitude, Year));
CREATE TABLE Kills (BeeState VARCHAR(255), BeeYear INTEGER, RiskFactorsReportedYear INTEGER, RiskFactorsReportedState VARCHAR(255), PRIMARY KEY (BeeState, BeeYear, RiskFactorsReportedYear, RiskFactorsReportedState), FOREIGN KEY (BeeState, BeeYear) REFERENCES Bee(State, Year), FOREIGN KEY (RiskFactorsReportedState, RiskFactorsReportedYear) REFERENCES RiskFactors(State, Year)); 
CREATE TABLE Parasite (Year INTEGER, State VARCHAR(255), PercentAffected DECIMAL, PRIMARY KEY (Year, State), FOREIGN KEY (State, Year) REFERENCES RiskFactors(State, Year));
CREATE TABLE Pesticide (Year INTEGER, State VARCHAR(255), LowEstimate DECIMAL, HighEstimate DECIMAL, PRIMARY KEY (Year, State), FOREIGN KEY (State, Year) REFERENCES RiskFactors(State, Year));
